version: '3'

services:
  # The Workers (3 Copies)
  flask_worker:
    build: .
    deploy:
      replicas: 3

  # The Traffic Cop (Nginx)
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_worker